version: "3"
services:
  db:
    container_name: mongodb
    image: mongo:4.0
    restart: always
    ports:
      - '27019:27019'
  qawolf:
    container_name: qawolf
    image: qabuild:latest
    restart: always
    environment:
      - QAW_HEADLESS=true
