apiVersion: apps/v1
kind: Deployment
metadata:
  name: "todo-app"

spec:
  selector:
    matchLabels:
      app: "todo-app"
  replicas: 4
  template:
    metadata:
      labels:
        app: "todo-app"
    spec:
      containers:
      - image: cimg/2020.05
        imagePullPolicy: Always
        name: "todo-app"
        ports:
         - containerPort: 80  